visitors = ['Dasha', 'Mom', 'Granny']
print('Hello, dear ' + visitors[0] + '! I want to invite you to my dinner!')
print(visitors[1] + ' would you like to visit my dinner?')
print(visitors[2] + ' is going to be there!')
print(visitors[0] + ' cannot come to my dinner!')
visitors[0] = 'Sister'
print('New list of visitors: ' + str(visitors) + '\n')
print(visitors[1] + ' would you like to visit my dinner?')
print(visitors[2] + ' is going to be there!')
print(visitors[0] + ' will come too!')
print('\nThere are more places for visitors!')
visitors.insert(0, 'Vitalik')
visitors.insert(2, 'Dasha')
visitors.append('Gosha')
print('Newest list of visitors: ' + str(visitors))
print(visitors[0] + ', ' + visitors[2] + ', ' + visitors[-1] + ' will join us!')
print('\nThere are only two places!:(')
g = visitors.pop()
print('Sorry ' + g)
v = visitors.pop(0)
print('Sorry ' + v)
s = visitors.pop(0)
print('Sorry ' + s)
d = visitors.pop(0)
print('Sorry ' + d)
print('Dear ' + visitors[0] + ' everyting is alright!')
print('Hello ' + visitors[1] + '! You can come')
print('The finale list of visitors: ' + str(visitors))
del visitors[0]
del visitors[0]
print(visitors)
